:icons: font

= HTL-Leonding KeyCloak Authentication Demos

IMPORTANT: These demos show a working, minimal setup to help you get started and are thus _not_ considered production ready!

This repository contains the following demo applications -- *relevant for POSE & SYP* -- for performing a login via our KeyCloak instance and accessing the LDAP user information:

* SPA & WebAPI
** The WebAPI for these projects is shared (link:./Shared_WebAPI[`Shared_WebAPI`])
** These samples also include simple, role based authorization
** Demos:
*** Blazor WASM (link:./Blazor_WebAPI[`Blazor_WebAPI`])
*** Angular (link:./Angular_WebAPI[`Angular_WebAPI`])
* Server-side-rendering (link:./SSR_only[`SSR_only`])
** Pure server side rendering without client interactivity
* Client- & Server side 'auto' rendering (link:./Blazor_CSR_and_SSR[`Blazor_CSR_and_SSR`])
** Blazor application which runs SSR while it downloads the WASM in the background and switches automatically to CSR once done
* link:./NodeJS[`NodeJS WebAPI`] example
** Token has to be retrieved in client application!

CAUTION: Some demos (with extended functionality) require you to set the `ClientSecret` for the LDAP service which you can request from a teacher if you have a good reason for regular token validation & role determination not being sufficient in your application
Look for the `TODO`.

All demos (except Angular of course) make use of the following NuGet packages:

* https://www.nuget.org/packages/HTLLeonding.Utility.LeoAuth[`HTLLeonding.Utility.LeoAuth`]
** Contains utility classes for processing a `ClaimsPrincipal` and extracting data like department, teacher/student, name, etc.
** Also contains a `PersistentAuthenticationStateProvider` required when using Blazor with automatic render mode
* https://www.nuget.org/packages/HTLLeonding.Utility.LeoAuth.Server[`HTLLeonding.Utility.LeoAuth.Server`]
** Provides some additional resources for backends -- cannot be included client side!
*** Especially a `PersistingRevalidatingAuthenticationStateProvider` required when using Blazor with automatic render mode
** It is sufficient to reference this package to get `LeoAuth` transitively

NOTE: These packages are _not_ required, you can implement the processing of the LDAP claims yourself as well.
